# Generated by Django 4.2.3 on 2023-09-01 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Text of the comment.')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='The time when the comment was created.')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the project.', max_length=200)),
                ('description', models.TextField(help_text='Description or details of the project.')),
                ('start_date', models.DateField(help_text='The start date of the project.')),
                ('end_date', models.DateField(help_text='The expected end date of the project.')),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expertise', models.CharField(help_text='Area of expertise of the supervisor.', max_length=200)),
            ],
        ),
    ]
