# Generated by Django 4.2.3 on 2023-09-06 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor',
            name='user',
            field=models.OneToOneField(help_text='The associated user for this supervisor.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='students',
            field=models.ManyToManyField(help_text='Students associated with this project.', related_name='student_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='supervisor',
            field=models.ForeignKey(help_text='The supervisor overseeing this project.', on_delete=django.db.models.deletion.CASCADE, related_name='supervised_projects', to='project.supervisor'),
        ),
        migrations.AddField(
            model_name='comment',
            name='project',
            field=models.ForeignKey(help_text='The project this comment is associated with.', on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(help_text='The user who made this comment.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
